[package]
name = "e2_edec"
version = "0.1.0"
authors = ["Sinon <daviru007@icloud.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"