name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Proto Dependency
      run: sudo apt-get install protobuf-compiler
    - name: Tauri Dependency
      run: npm install -g @tauri-apps/cli
    - name: Build
      run: cargo tauri build --verbose
